# Generated by Django 4.2.7 on 2023-11-21 22:34

import django.core.validators
from django.db import migrations, models
import pet_app.validator


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='bird',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bird',
            name='name',
            field=models.CharField(max_length=255, validators=[pet_app.validator.validate_name]),
        ),
        migrations.AlterField(
            model_name='bird',
            name='species',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=255, validators=[pet_app.validator.validate_name]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=255, validators=[pet_app.validator.validate_name]),
        ),
        migrations.AlterField(
            model_name='exotic_animal',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='exotic_animal',
            name='name',
            field=models.CharField(max_length=255, validators=[pet_app.validator.validate_name]),
        ),
        migrations.AlterField(
            model_name='exotic_animal',
            name='region_of_origin',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='owner',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(110)]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255, validators=[pet_app.validator.validate_name]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='number_of_pets',
            field=models.PositiveIntegerField(),
        ),
    ]
